### ISSUE TITLE
Reproduction issue

### ISSUE THREAD

**Issue by wwl2755** [JiaoyiZhang/Efficient-Disk-Learned-Index#1]
Hi,

It is very nice to have your excellent work here. And when I try to reproduce the result, I am stuck at the very beginning. I have the datasets prepared and just used the provided script to compile it. But it seems some files are missing here. Could you kindly help to solve this issue? Thank you!

Efficient-Disk-Learned-Index$ bash scripts/build_benchmark.sh
CMake Error at CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /home/Efficient-Disk-Learned-Index/libraries/LeCo/src

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:32 (add_subdirectory):
  The source directory

    /home/Efficient-Disk-Learned-Index/libraries/LeCo/thirdparty/fsst

  does not contain a CMakeLists.txt file.

**Comment by JiaoyiZhang** [comment]
Hi,

Thanks for your interest in our work!
The missing files have now been uploaded to the appropriate directories. Please check the corresponding directories.

**Comment by wwl2755** [comment]
Thank you so much for your kind help. Could you also double-check the CMake file in **LeCO/src**? It seems the file is still missing there.

Here is the error message when I use the command 'bash scripts/build_benchmark.sh':

CMake Error at CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /home/Efficient-Disk-Learned-Index/libraries/LeCo/src

  does not contain a CMakeLists.txt file.
  
  I tried to use the file from the original repo (https://github.com/yhliu918/Learn-to-Compress/tree/main/src), but it still does not work,
  
  In file included from /home/Efficient-Disk-Learned-Index/libraries/LeCo/src/../headers/lr.h:8:0,
                 from /home/Efficient-Disk-Learned-Index/libraries/LeCo/src/../headers/RANSAC.h:11,
                 from /home/Efficient-Disk-Learned-Index/libraries/LeCo/src/RANSAC.cpp:1:
/home/Efficient-Disk-Learned-Index/libraries/LeCo/src/../headers/string/leco_uint256.h:14:10: error: specialization of ‘std::is_arithmetic<__int128 unsigned>’ after instantiation
   struct is_arithmetic<__uint128_t> : std::true_type
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/Efficient-Disk-Learned-Index/libraries/LeCo/src/../headers/string/leco_uint256.h:14:10: error: redefinition of ‘struct std::is_arithmetic<__int128 unsigned>’

**Comment by JiaoyiZhang** [comment]
The CMake file in the LeCo folder has been uploaded before, please check it again.
Please let me know what went wrong with the source code if this is not the file you mentioned.
